### ISSUE TITLE
Support Alfred 2

### ISSUE THREAD

**Issue by arturopie** [ecbrodie/pomodoro-alfred#3]
I get the following when trying to install this workflow in Alfred 2

![image](https://cloud.githubusercontent.com/assets/762752/20201829/ecf20350-a788-11e6-87ed-1fe7f20b7f7d.png)

**Comment by ecbrodie** [comment]
This will require me creating the workflow (essentially, `info.plist`) in an Alfred 2 installation, as any workflow created in Alfred 3 will automatically not be backwards compatible. I will need to see if having 2 active Alfred installations on a single machine is possible. If not, then I will need to get an alternate Mac account set up to re-build the workflow on Alfred 2.

Pull requests are also welcome.

**Comment by ecbrodie** [comment]
I've decided that I do not have interest in maintaining backwards compatibility with Alfred 2 due to the high complexity in maintaining two info.plist files. I'm open to outside contributions. Until then, I'm closing this.
